In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
YEAR = 2020

In [3]:
data = pd.read_csv('https://github.com/nflverse/nflverse-data/releases/download/pbp/' \
                   'play_by_play_' + str(YEAR) + '.csv.gz',
                   compression= 'gzip', low_memory= False)

In [4]:
data

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,1,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,NaN,NaN,NaN,...,0,1,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,39,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0,1,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,54,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0,1,1.294838,0.50337,4.275047,2.0,0.619306,0.239695,0.515058,48.494154
3,93,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0,1,0.857214,NaN,NaN,NaN,NaN,NaN,0.413357,-41.335732
4,118,2020_01_ARI_SF,2020091311,SF,ARI,REG,1,SF,home,ARI,...,0,1,-0.454665,NaN,NaN,NaN,NaN,NaN,0.446920,-44.692025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47700,4280,2020_21_KC_TB,2021020700,TB,KC,POST,21,KC,away,TB,...,0,1,-4.266047,NaN,NaN,NaN,NaN,NaN,0.904422,9.557813
47701,4307,2020_21_KC_TB,2021020700,TB,KC,POST,21,TB,home,KC,...,0,1,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47702,4328,2020_21_KC_TB,2021020700,TB,KC,POST,21,TB,home,KC,...,0,1,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47703,4349,2020_21_KC_TB,2021020700,TB,KC,POST,21,TB,home,KC,...,0,1,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47704,4370,2020_21_KC_TB,2021020700,TB,KC,POST,21,TB,home,KC,...,0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
def passer_rating(cmp, yds, tds, ints, att):
    a = (cmp/att - .3) * 5
    b = (yds/att - 3) * .25
    c = (tds/att) * 20
    d = 2.375 - (25 * ints/att)

    return ((a+b+c+d)/6) * 100

def anya(pass_yds, tds, ints, sack_yds, sacks, pass_attempts):
    return (pass_yds + (tds * 20) - (ints * 45) - sack_yds)/(pass_attempts + sacks)

In [ ]:
#decided to focus on passer rating, ANY/A and EPA as stats.